export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";
export const FETCHING_FOREX_DATA = "FETCHING_FOREX_DATA";
export const FETCHING_FOREX_DATA_SUCCESS = "FETCHING_FOREX_DATA_SUCCESS";
export const FETCHING_FOREX_DATA_FAIL = "FETCHING_FOREX_DATA_FAIL";
